arch:
    - amd64
    - ppc64le
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "14"
  - "node"
sudo: false
install:
  - npm install
script:
  - if [ "x$BUNDLER" = "x" ]; then npm test; fi
  - if [ "x$BUNDLER" != "x" ]; then npm run test-karma; fi
# only run karma tests for one node version
matrix:
  include:
  - name: "Browser Unit Tests (webpack)"
    node_js: "14"
    env: BUNDLER=webpack
  - name: "Browser Unit Tests (browserify)"
    node_js: "14"
    env: BUNDLER=browserify
notifications:
  email:
    on_success: change
    on_failure: change
