language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "node"
sudo: false
install: npm install
script:
  - if [ "x$BUNDLER" = "x" ]; then npm test; fi
  - if [ "x$BUNDLER" != "x" ]; then npm run test-karma; fi
# only run karma tests for one node version
matrix:
  include:
  - node_js: "10"
    env: BUNDLER=webpack
  - node_js: "10"
    env: BUNDLER=browserify
notifications:
  email:
    on_success: change
    on_failure: change
